SELECT nombre, lugar
    FROM EI.Alumno
    WHERE nombre LIKE 'M%'
    AND lugar LIKE '_____%' AND lugar NOT LIKE 'P%';
    
SELECT nombre, web
    FROM MF.COMPAÑIA
    WHERE web LIKE '%et%' AND web LIKE '%com';
    
SELECT *
    FROM MF.LLAMADA;

SELECT LL.TF_DESTINO
    FROM MF.LLAMADA LL
    WHERE LL.TF_ORIGEN = '666010101' AND EXTRACT(YEAR FROM LL.FECHA_HORA) = '2006';
    
select *
    from ei.profesor;
    
select *
    from ei.asignatura;
    
SELECT *
FROM ei.asignatura asig INNER JOIN ei.profesor prof
ON asig.prof=prof.npr;


SELECT *
FROM MF.TARIFA;

SELECT T.TARIFA, CIA.NOMBRE , T.COSTE  
    FROM MF.TARIFA T INNER JOIN MF.COMPAÑIA CIA
    ON (T.COMPAÑIA = CIA.CIF)
    
    WHERE T.DESCRIPCION LIKE '%compañía%';
    
SELECT *
    FROM MF.CLIENTE;
    
SELECT C.NOMBRE, T.NUMERO
    FROM (MF.TELEFONO T INNER JOIN MF.CLIENTE C ON (T.CLIENTE = C.DNI))
        INNER JOIN MF.TARIFA TAR USING(TARIFA,COMPAÑIA)
        WHERE TAR.COSTE<0.20 AND T.TIPO = 'C';
        
/*MF. 11*/

SELECT *
    FROM MF.tarifa;

SELECT C.NOMBRE
    FROM (MF.CLIENTE C INNER JOIN MF.TELEFONO T ON C.DNI=T.CLIENTE);

SELECT C.NOMBRE
    FROM (MF.CLIENTE C INNER JOIN MF.TELEFONO T ON C.DNI=T.CLIENTE)
        INNER JOIN MF.COMPAÑIA CIA ON CIA.CIF=T.COMPAÑIA
            WHERE CIA.NOMBRE='Aotra' AND T.TARIFA = (SELECT TARIFA
                                                            FROM MF.TARIFA TAR INNER JOIN MF.TELEFONO TEL USING(tarifa,compañia)
                                                                WHERE TEL.NUMERO='654123321'
                                                            );
                                                            
SELECT *
FROM MF.LLAMADA;

/*MF 22*/
SELECT CIA.NOMBRE
    FROM (MF.LLAMADA LL INNER JOIN MF.TELEFONO T ON LL.TF_ORIGEN = T.NUMERO)
        INNER JOIN MF.COMPAÑIA CIA ON CIA.CIF= T.COMPAÑIA
            WHERE TO_CHAR(LL.FECHA_HORA, 'DD/MM/YYYY')='16/10/2006'
    GROUP BY CIA.NOMBRE
    HAVING COUNT(*)>=ALL(SELECT COUNT(*) FROM MF.LLAMADA LL INNER JOIN MF.TELEFONO T ON LL.TF_ORIGEN=T.NUMERO
    WHERE TO_CHAR(LL.FECHA_HORA,'DD/MM/YYYY')='16/10/2006' GROUP BY CIA.NOMBRE);
    
/*MF 23*/
SELECT DISTINCT T.NUMERO,C.NOMBRE
    FROM (MF.TELEFONO T INNER JOIN MF.CLIENTE C ON C.DNI=T.CLIENTE)
        INNER JOIN MF.LLAMADA LL ON LL.TF_ORIGEN=T.NUMERO
        WHERE LL.TF_ORIGEN='654345345' AND
            TO_CHAR(LL.FECHA_HORA,'MM/YYYY')='10/2006';
            
/*MF 26*/
SELECT CLTE.NOMBRE, COUNT (*)
    FROM MF.LLAMADA LLAM INNER JOIN MF.TELEFONO TEL ON LLAM.TF_ORIGEN=TEL.NUMERO
    INNER JOIN MF.CLIENTE CLTE ON CLTE.DNI=TEL.CLIENTE
    GROUP BY CLTE.NOMBRE
    HAVING COUNT(*) > 5;
    
/*MF 27*/
SELECT CLTE.NOMBRE AS CLIENTE, AVG(TAR.COSTE) AS MEDIA
    FROM MF.CLIENTE CLTE INNER JOIN MF.TELEFONO TEL ON TEL.CLIENTE=CLTE.DNI
    INNER JOIN MF.TARIFA TAR USING (TARIFA, COMPAÑIA)
    GROUP BY CLTE.NOMBRE
    HAVING AVG(TAR.COSTE)>=ALL (SELECT AVG(COSTE) FROM MF.TARIFA);

/*mf 28*/
SELECT CLTE.NOMBRE AS NOMBRE
    FROM MF.LLAMADA LLAM INNER JOIN MF.TELEFONO TEL ON LLAM.TF_ORIGEN=TEL.NUMERO
    INNER JOIN MF.TARIFA TAR USING(TARIFA, COMPAÑIA)
    INNER JOIN MF.CLIENTE CLTE ON TEL.CLIENTE=CLTE.DNI
    WHERE LLAM.TF_DESTINO IN(SELECT TEL.NUMERO FROM MF.TELEFONO TEL 
        INNER JOIN MF.COMPAÑIA CIA ON TEL.COMPAÑIA=CIA.CIF
    WHERE CIA.NOMBRE='KIETOSTAR')
    GROUP BY CLTE.NOMBRE
    HAVING SUM(LLAM.DURACION/60 * TAR.COSTE) <100;