/*EI 24. Obtener, mediante una consulta correlacionada, los nombres de las asignaturas que tienen
recomendadas 2 o más asignaturas.*/
SELECT P1.NOMBRE
FROM EI.PROFESOR P1
WHERE (SELECT COUNT(*) FROM EI.PROFESOR P2 WHERE P1.ant < P2.ant) >=5;

SELECT A.nombre, M.año, COUNT(M.FEB_JUN) AS Presentados, AVG(M.FEB_JUN) AS Media
FROM EI.MATRICULA M INNER JOIN EI.ASIGNATURA A USING(IDASIG)
GROUP BY A.nombre, M.año;

SELECT A.nombre, ASIG.nombre
FROM (EI.ALUMNO A INNER JOIN EI.MATRICULA M ON A.nAL = M.alum) INNER JOIN EI.ASIGNATURA ASIG USING(IDASIG)
GROUP BY A.nombre, ASIG.nombre
HAVING COUNT(*) >= 3;

SELECT A.nombre
FROM EI.ALUMNO A INNER JOIN EI.MATRICULA M ON A.nAL = M.alum
WHERE M.año = 2002
GROUP BY A.nombre
HAVING AVG(M.feb_jun) > 5;

/*MF 25*/
SELECT CL.NOMBRE AS CLIENTE, SUM(LL.DURACION) AS DURACION
FROM MF.LLAMADA LL INNER JOIN MF.TELEFONO T ON LL.TF_ORIGEN = T.NUMERO
INNER JOIN MF.CLIENTE CL ON T.CLIENTE = CL.DNI
WHERE LL.TF_DESTINO IN (SELECT TE.NUMERO
            FROM MF.TELEFONO TE INNER JOIN MF.CLIENTE CI ON TE.CLIENTE=CI.DNI WHERE CI.PROVINCIA='Jaén')
        AND LL.TF_ORIGEN IN (SELECT TE.NUMERO
            FROM MF.TELEFONO TE INNER JOIN MF.CLIENTE CI ON TE.CLIENTE=CI.DNI WHERE CI.PROVINCIA='La Coruña')
GROUP BY CL.NOMBRE;